### ISSUE TITLE
Fork instead!

### ISSUE THREAD

**Issue by StethoSaysHello** [Filza2/Brute-Force-TikTok#1]
You should fork the [original](https://github.com/vv1ck/Brute-force-Tiktok) instead of reposting it!
At least add the README stuff if you are gonna skid, lmao.

**Comment by Filza2** [comment]
I’m and my friend the developer’s for this tool my friend 😂💔 LOOK in the src my user TweakPY - Filza2

**Comment by StethoSaysHello** [comment]
OH!! LMAO MY BAD
I'm over here like "why are there two of the same project, tf"
Sorry for the confusion then 😂
